name: Commit Now

on:
  workflow_dispatch:
    inputs:
      email:
        description: "Email"
        required: true
        default: "agungprasetio878@gmail.com"
      username:
        description: "Username"
        required: true
        default: "prasagungg"
      commit:
        description: "Commit"
        required: true
        default: "Gimmick"
      limit:
        description: "Limit Commit"
        required: true
        default: 20
  push:
    branches:
      - main

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set Config
        run: |
          git config --global user.email "agungprasetio878@gmail.com"
          git config --global user.name "Broken Coder"
          git add -A

          arr[0]="Gimmick ðŸ˜"
          arr[1]="Gimmick ðŸ˜±"
          arr[2]="Gimmick ðŸŽï¸"
          arr[3]="Gimmick ðŸ‘€"
          arr[4]="Gimmick ðŸ™"
          arr[5]="Gimmick ðŸ’¦"
          arr[6]="Gimmick ðŸ"
          arr[7]="Gimmick ðŸ¤–"
          arr[8]="Gimmick â˜•"
          arr[9]="Gimmick ðŸ‘»"

          rand=$[$RANDOM % ${#arr[@]}]

          git commit -m "${arr[$rand]}"

      - name: DO It
        run: |
          for i in {0..${{ github.event.inputs.limit }}}
          do
            cat > GIMMICK
            d=$i+`date '+%Y-%m-%dT%H:%M:%SZ'`
            echo $d > GIMMICK
            git add -A
            git commit -m "${{ github.event.inputs.commit }}"
          done

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.TOKEN }}
